services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  GeoDataGouv\Config\ConfigManager:

  GeoDataGouv\DataFlowType\DataGouvImportLocationsDataFlowType:
    tags:
      - { name: coderhapsodie.dataflow.type }

  GeoDataGouv\DataFlow\FileReader:

  GeoDataGouv\DataFlow\GeocodingFileReader:

  GeoDataGouvBundle\Rest\DefaultController:
    autoconfigure: false
    autowire: false
    public: true
    parent: 'ezpublish_rest.controller.base'

  geo_data_gouv.rest.controller:
    alias: GeoDataGouvBundle\Rest\DefaultController
    public: true

  geo_data_gouv.rest.value_object_visitor.LocationContent:
    autoconfigure: false
    autowire: false
    public: true
    parent: ezpublish_rest.output.value_object_visitor.base
    class: eZGeoDataGouvBundle\Rest\ValueObjectVisitor\LocationContent
    arguments: ['@ezpublish.translation_helper']
    tags:
      - { name: ezpublish_rest.output.value_object_visitor, type: eZGeoDataGouvBundle\Rest\Values\LocationContent }
